config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'
  # devise_for :users
  # root to: 'homes#top'
  # get 'home/about' => 'homes#about', as: 'about'

  # resources :posts, only: [:new, :create, :index, :show, :destroy] do
  #   resources :post_comments, only: [:create, :destroy]
  #   resource :bookmarks, only: [:create, :destroy]
  # end
  # resources :users, only: [:index, :show, :edit, :update]

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:destroy]
  end

  scope module: :public do
    devise_for :users
    root to: 'homes#top'
    get 'home/about' => 'homes#about', as: 'about'
    get 'search' => 'searches#search', as: 'search'
    get 'post/bookmarked_index' => 'posts#bookmarked_index', as: 'bookmarked'
    get 'post/categorized/:category_id' => 'posts#categorized', as: 'categorized'
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :bookmark, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  belongs_to :category
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :image, presence: true
  validates :body, presence: true
  validates :category_id, presence: true

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  # scope :order_by_bookmark_count -> {joins(:bookmarks).order(bookmarks.count: :)  all.sort_by { |post| post.bookmarks.count }.reverse!}

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def bookmarked_by?(user)
    if user.present?
      bookmarks.exists?(user_id: user.id)
    end
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :votes

  validates :name, presence: true, length: {in: 2..20}, uniqueness: true
  validates :introduction, length: {maximum: 140}
  validates :favorite_animal, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'
  
  def index
    @posts = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_dashboards_path, notice: '投稿を削除しました。'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  
  def index
    @users = User.all
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_dashboards_path, notice: 'ユーザーを削除しました。'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_authentication
  # before_action:authenticate_user!, except: [:top, :about, :index, :show], unless: :admin_controller?

  private

  def configure_authentication
    if admin_controller?
      authenticate_admin!
    else
      authenticate_user! unless action_is_public?
    end
  end

  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end

  def action_is_public?
    controller_name == 'posts' && (action_name == 'index' || action_name == 'show')
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    bookmark = current_user.bookmarks.new(post_id: post.id)
    bookmark.save
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:post_id])
    bookmark = current_user.bookmarks.find_by(post_id: post.id)
    bookmark.destroy
    redirect_to post_path(post.id)
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    post_comment = current_user.post_comments.new(post_comment_params)
    post_comment.post_id = post.id
    post_comment.save
    redirect_to post_path(post.id)
  end

  def destroy
    post_comment = PostComment.find(params[:id])
    post_comment.destroy
    redirect_to post_path(post_comment.post_id)
  end

  private

def post_comment_params
  params.require(:post_comment).permit(:comment)
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    @categorys = Category.all
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "投稿に成功しました"
      redirect_to posts_path
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  def edit
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

private

def post_params
  params.require(:post).permit(:body, :image, :date, :place)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "更新に成功しました"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :favorite_animal)
  end

end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/posts/index.html.erb
<h1>投稿一覧</h1>
<ul>
  <% @posts.each do |post| %>
    <li>
      <%= image_tag post.get_image(200,200) %> - <%= post.body %> 
      <%= link_to '投稿を削除', admin_post_path(post), method: :delete, data: { confirm: '本当に削除しますか？' } %>
    </li>
    <% post.post_comments.each do |post_comment| %>
        <%= post_comment.comment %>
        <%= link_to 'コメントを削除', admin_post_comment_path(post_comment), method: :delete, data: { confirm: '本当に削除しますか？' } %>
    <% end %>
  <% end %>
</ul>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧</h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.name %> - <%= user.email %>
      <%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除しますか？' } %>
    </li>
  <% end %>
</ul>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<div>
  <table class="post-index">
    <thead>
      <tr>
        <th>ユーザー画像</th>
        <th>画像</th>
        <th>本文</th>
        <th>コメント件数</th>
        <th>ブックマーク</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
      <tr>
        <td>
        <%= link_to user_path(post.user.id) do %>
          <%= image_tag post.user.get_profile_image(40, 40) %>
        <% end %>
        </td>
        <td>
          <%= link_to post_path(post.id) do %>
            <%= image_tag post.get_image(200,200) %>
          <% end %>
        </td>
        <td>
          <%= post.body %>
        </td>
        <td>
         <p><%= link_to "#{post.post_comments.count} コメント", post_path(post.id) %></p>
        </td>
        <td>
        <% if post.bookmarked_by?(current_user) %>
          <p>
            <%= link_to post_bookmarks_path(post), method: :delete do %>
              ♥<%= post.bookmarks.count %>
            <% end %>
          </p>
        <% else %>
          <p>
            <%= link_to post_bookmarks_path(post), method: :post do %>
              ♡<%= post.bookmarks.count %>
            <% end %>
          </p>
        <% end %>
        </td>
      </tr>
      <% end %> 
    </tbody>
  </table>
<div>

app/views/posts/new.html.erb
<h1>投稿フォーム</h1>

<% if @post.errors.any? %>
  <%= @post.errors.count %>件のエラーが発生しました
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @post do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  
  <h4>カテゴリー</h4>
  <% @categorys.each do |category| %>
    <%= f.radio_button :category_id, :"#{category.id}" %>
    <%= f.label :category_id, "#{category.name}", value: :"#{category.id}" %>
  <% end %>

  <h4>本文</h4>
  <%= f.text_area :body %>
  <h4>日時</h4>
  <%= f.text_field :date %>
  <h4>場所</h4>
  <%= f.text_field :place %>
  <%= f.submit '投稿' %>
<% end %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>

<div>
  <%= image_tag @post.get_image(500,200) %>

  <p>本文：<%= @post.body %></p>
  <p></p>
  <p>
    投稿ユーザー画像：
    <%= link_to user_path(@post.user.id) do %>
      <%= image_tag @post.user.get_profile_image(100, 100) %>
    <% end %>
  </p>
  <p>
    ユーザーネーム：
    <%= link_to user_path(@post.user.id) do %>
      <%= @post.user.name %>
    <% end %>
  </p>
  <p>投稿日：<%= @post.created_at.strftime('%Y/%m/%d') %></p>
  <% if current_user == @post.user %>
    <%= link_to "削除", post_path(@post.id), method: :delete %>
  <% end %>
</div>

<div>
  <% if @post.bookmarked_by?(current_user) %>
    <p>
      <%= link_to post_bookmarks_path(@post), method: :delete do %>
        ♥<%= @post.bookmarks.count %> ブックマーク
      <% end %>
    </p>
  <% else %>
    <p>
      <%= link_to post_bookmarks_path(@post), method: :post do %>
        ♡<%= @post.bookmarks.count %> ブックマーク
      <% end %>
    </p>
  <% end %>

  <p>コメント件数：<%= @post.post_comments.count %></p>
  <% @post.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <% if current_user == post_comment.user %>
      <%= link_to "削除", post_post_comment_path(post_comment.id), method: :delete %>
    <% end %>
  <% end %>
</div>

<div>
  <%= form_with model: [@post, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>

<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>
  <h4>プロフィール画像</h4>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <h4>名前</h4>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <h4>自己紹介</h4>
  <%= f.text_area :introduction, autofocus: true, id:"inputName", placeholder:"自己紹介"%>
  <h4>好きな動物</h4>
  <%= f.text_field :favorite_animal, autofocus: true, id:"inputName", placeholder:"好きな動物"%>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧（管理）</h1>




<% @users.each do |user| %>
  <div>
    <p>
    ユーザー画像：<%= image_tag user.get_profile_image(100, 100) %>
    </p>
    <p>
      ユーザーネーム：<%= user.name %>
    </p>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>
<p>
  ユーザー画像：<%= image_tag @user.get_profile_image(100, 100) %>
</p>
<p>
  ユーザーネーム：<%= @user.name %>
</p>
<p>
  自己紹介：<%= @user.introduction %>
</p>
<p>
  好きな動物：<%= @user.favorite_animal %>
</p>

<p><%= link_to "プロフィール編集", edit_user_path(@user.id) %></p>

<% @posts.each do |post| %>
  <div>
    <%= link_to post_path(post.id) do %>
      <%= image_tag post.get_image(100,100) %>
    <% end %>
    <p>
    投稿ユーザー画像：<%= image_tag post.user.get_profile_image(100, 100) %>
    </p>
    <p>本文：<%= post.body %></p>
    <p>ユーザーネーム：<%= post.user.name %></p>
  </div>
<% end %>