config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'
  # devise_for :users
  # root to: 'homes#top'
  # get 'home/about' => 'homes#about', as: 'about'

  # resources :posts, only: [:new, :create, :index, :show, :destroy] do
  #   resources :post_comments, only: [:create, :destroy]
  #   resource :bookmarks, only: [:create, :destroy]
  # end
  # resources :users, only: [:index, :show, :edit, :update]

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:index, :destroy]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:destroy]
  end

  scope module: :public do
    devise_for :users
    root to: 'homes#top'
    get 'home/about' => 'homes#about', as: 'about'
    get 'search' => 'searches#search', as: 'search'
    get 'post/bookmarked_index' => 'posts#bookmarked_index', as: 'bookmarked'
    get 'post/categorized/:category_id' => 'posts#categorized', as: 'categorized'
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :bookmark, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  belongs_to :category
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :image, presence: true
  validates :body, presence: true
  validates :category_id, presence: true

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  # scope :order_by_bookmark_count -> {joins(:bookmarks).order(bookmarks.count: :)  all.sort_by { |post| post.bookmarks.count }.reverse!}

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def bookmarked_by?(user)
    if user.present?
      bookmarks.exists?(user_id: user.id)
    end
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :votes

  validates :name, presence: true, length: {in: 2..20}, uniqueness: true
  validates :introduction, length: {maximum: 140}
  validates :favorite_animal, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_authentication
  # before_action:authenticate_user!, except: [:top, :about, :index, :show], unless: :admin_controller?

  private

  def configure_authentication
    if admin_controller?
      authenticate_admin!
    else
      authenticate_user! unless action_is_public?
    end
  end

  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end

  def action_is_public?
    controller_name == 'posts' && (action_name == 'index' || action_name == 'show')
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    bookmark = current_user.bookmarks.new(post_id: post.id)
    bookmark.save
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:post_id])
    bookmark = current_user.bookmarks.find_by(post_id: post.id)
    bookmark.destroy
    redirect_to post_path(post.id)
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    post_comment = current_user.post_comments.new(post_comment_params)
    post_comment.post_id = post.id
    post_comment.save
    redirect_to post_path(post.id)
  end

  def destroy
    post_comment = PostComment.find(params[:id])
    post_comment.destroy
    redirect_to post_path(post_comment.post_id)
  end

  private

def post_comment_params
  params.require(:post_comment).permit(:comment)
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    @categorys = Category.all
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "投稿に成功しました"
      redirect_to posts_path
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  def edit
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

private

def post_params
  params.require(:post).permit(:body, :image, :date, :place)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "更新に成功しました"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :favorite_animal)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Zukan</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if admin_signed_in? %>
    <div class="text-right">
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zukan</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/3006deca4b.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm" style="background-color: #e3f2fd;">
      <nav class="navbar navbar-expand-lg navbar-light" >
        <div class="container ">
          <a class="navbar-brand pr-5" href="/posts">
            なんでもソーシャル生き物図鑑
          </a>
          <!-- 検索ボタン -->
          <div>
            <%= form_with url: search_path, local: true, method: :get do |f| %>
              <%= f.text_field :word %>
              <%= f.select :range, options_for_select([['Post'], ['User']]) %>
              <%= f.submit '検索', class: "mt-1 btn btn-primary" %>
            <% end %>
          </div>
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="ml-3 collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to(posts_path , class: 'nav-link') do %>
                    <i class="fa-solid fa-house"></i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to(new_post_path , class: 'nav-link') do %>
                    <i class="fa-solid fa-square-plus"></i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to(user_path(current_user.id) , class: 'nav-link') do %>
                    <i class="fa-solid fa-user"></i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to(bookmarked_path , class: 'nav-link') do %>
                    <i class="fa-solid fa-bookmark"></i>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to(destroy_user_session_path,  method: :delete, class: 'nav-link') do %>
                    <i class="fa-solid fa-right-from-bracket"></i>
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "TOP", posts_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <footer class="bg-dark text-white pt-4 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col text-center">
             <%= link_to "このサイトについて", about_path, class: "text-white-50" %>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>